name: 联合公社
v4port: 2024
v6port: 2024
sql_mode: sqlite
sql_url: sqlite://sqlite.db
email_config:
  mine_email: mcu@xiaochen.site
  smtp_server: smtpdm.aliyun.com
  email_password: MCusmtp123456
register_user:
  email: admin
  password: uaixvgeo
